title: Stack Problems
description: My Personal Stack Problems
author: Alex Schenk
github: https://github.com/ajs1592
about: I'm a Computer Science teacher and technology enthusiast in St. Louis, MO.
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    
    - icon: fa-twitter
      link: "https://twitter.com/alexjschenk?lang=en"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/alexander-schenk-75397012a/"
   
    - icon: fa-github
      link: "https://github.com/ajs1592"

share:
  twitter_username: alexjschenk
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: portfolio/about/
    - text: My Projects
      url: portfolio/projects/
    - text: XML Feed
      url: /feed.xml

url: "https://github.com/ajs1592/portfolio/"
baseurl: "/portfolio"
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
